RIG.Model = Model("models/viper/mw/rigs/sleeves/mp_western_vm_arms_fireteam_west.mdl")
RIG.Skins = {
    "Camo 1",
    "Camo 2",
    "Camo 3",
    "Camo 4",
    "Camo 5",
    "Camo 6",
    "Camo 7",
    "Camo 8",
    "Camo 9",
    "Camo 10",
    "Camo 11",
    "Camo 12",
    "Camo 13",
    "Camo 14",
    "Camo 15",
    "Camo 16",
    "Camo 17",
    "Camo 18",
    "Camo 19",
    "Camo 20",
    "Camo 21",
    "Camo 22",
    "Camo 23",
    "Camo 24",
    "Camo 25",
    "Camo 26"
}
RIG.Name = "MW19 - MilSim (Western)"