// Created by Crowbar 0.74

$modelname "viper/mw/attachments/mcharlie/attachment_vm_ar_mcharlie_xmags2.mdl"

$bodygroup "grip"
{
	studio "attachment_vm_ar_mcharlie_xmags2.smd"
}


$surfaceprop "default"

$contents "solid"

$illumposition 0 0 0

$mostlyopaque

$cdmaterials "viper\mw\attachments\"
$cdmaterials "viper\MW\weapons\mcharlie\"

$cbox 0 0 0 0 0 0

$bbox -1.01 -8.449 0 27.788 0.643 64.32

$definebone "tag_mag_attach" "" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "j_mag1" "tag_mag_attach" -1.323 0 0.184 0 0 0 0 0 0 0 0 0
$definebone "j_mag2" "tag_mag_attach" -1.323 0 0.184 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_01" "j_mag1" 0 -0.127 1.693 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_02" "j_mag1" 0 0.121 1.531 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_03" "j_mag1" 0.007 -0.127 1.363 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_04" "j_mag1" 0.008 0.119 1.202 0 0 0 0 0 0 0 0 0
$definebone "tag_origin" "" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "tag_view" "tag_origin" -0.106 0 64.32 0 0 0 0 0 0 0 0 0
$definebone "tag_ads" "tag_view" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "tag_torso" "tag_ads" -0.904 0 -11.806 0 0 0 0 0 0 0 0 0
$definebone "tag_weapon" "tag_torso" 14.188001 0 0.141998 0 0 0 0 0 0 0 0 0
$definebone "j_gun" "tag_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "tag_sling" "j_gun" -10.412 0 0 0 0 0 0 0 0 0 0 0
$definebone "j_basespring" "j_mag1" 0.674 -0.016 -4.77 -73.393572 180.000005 180.000005 0 0 0 0 0 0
$definebone "j_bullet_05" "j_mag1" 0.010931 -0.156082 1.219293 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_06" "j_mag1" 0.006973 0.11498 1.043284 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_07" "j_mag1" 0.013147 -0.156076 0.882284 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_08" "j_mag1" 0.011894 0.124113 0.711288 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_09" "j_mag1" 0.01185 -0.156116 0.548284 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_10" "j_mag1" 0.009906 0.125014 0.385284 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_11" "j_mag1" 0.014855 -0.1561 0.218284 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_12" "j_mag1" 0.012971 0.118108 0.050288 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_13" "j_mag1" 0.033799 -0.155943 -0.113708 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_14" "j_mag1" 0.027133 0.117976 -0.288712 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_15" "j_mag1" 0.052955 -0.155952 -0.445712 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_16" "j_mag1" 0.050934 0.117975 -0.620712 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_17" "j_mag1" 0.049113 -0.155989 -0.779709 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_18" "j_mag1" 0.046953 0.117968 -0.954705 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_19" "j_mag1" 0.08293 -0.156007 -1.106705 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_20" "j_mag1" 0.081171 0.117968 -1.281709 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_21" "j_mag1" 0.12283 -0.156094 -1.437709 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_22" "j_mag1" 0.121957 0.117988 -1.612705 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_23" "j_mag1" 0.157932 -0.155872 -1.772709 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_24" "j_mag1" 0.15588 0.117969 -1.946712 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_25" "j_mag1" 0.208129 -0.155954 -2.097709 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_26" "j_mag1" 0.206131 0.118021 -2.272815 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_27" "j_mag1" 0.264029 -0.156109 -2.423709 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_28" "j_mag1" 0.261799 0.118021 -2.598712 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_29" "j_mag1" 0.324799 -0.155906 -2.753811 0 0 0 0 0 0 0 0 0
$definebone "j_bullet_30" "j_mag1" 0.322798 0.117988 -2.928808 0 0 0 0 0 0 0 0 0
$definebone "j_mag_follower" "j_basespring" 1.497441 -0.000052 -0.011369 0 0 0 0 0 0 0 0 0

$bonemerge "tag_mag_attach"
$bonemerge "j_mag1"
$bonemerge "j_mag2"
$bonemerge "j_bullet_01"
$bonemerge "j_bullet_02"
$bonemerge "j_bullet_03"
$bonemerge "j_bullet_04"
$bonemerge "j_basespring"
$bonemerge "j_bullet_05"
$bonemerge "j_bullet_06"
$bonemerge "j_bullet_07"
$bonemerge "j_bullet_08"
$bonemerge "j_bullet_09"
$bonemerge "j_bullet_10"
$bonemerge "j_bullet_11"
$bonemerge "j_bullet_12"
$bonemerge "j_bullet_13"
$bonemerge "j_bullet_14"
$bonemerge "j_bullet_15"
$bonemerge "j_bullet_16"
$bonemerge "j_bullet_17"
$bonemerge "j_bullet_18"
$bonemerge "j_bullet_19"
$bonemerge "j_bullet_20"
$bonemerge "j_bullet_21"
$bonemerge "j_bullet_22"
$bonemerge "j_bullet_23"
$bonemerge "j_bullet_24"
$bonemerge "j_bullet_25"
$bonemerge "j_bullet_26"
$bonemerge "j_bullet_27"
$bonemerge "j_bullet_28"
$bonemerge "j_bullet_29"
$bonemerge "j_bullet_30"
$bonemerge "j_mag_follower"


$poseparameter "bullets_offset" 0 30 loop 0

$animation "a_bullets_idle_to_sub_corrective_animation" "attachment_vm_ar_mcharlie_xmags2_anims\a_bullets_idle_to_sub_corrective_animation.smd" {
}

$animation "a_delta_bullets_additive_for_offset_corrective_animation" "attachment_vm_ar_mcharlie_xmags2_anims\a_delta_bullets_additive_for_offset_corrective_animation.smd" {
}

$animation "bullets_idle_to_sub" "attachment_vm_ar_mcharlie_xmags2_anims\bullets_idle_to_sub.smd" {
	fps 30
}

$animation "a_bullets_idle_to_sub" "attachment_vm_ar_mcharlie_xmags2_anims\a_bullets_idle_to_sub.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_bullets_idle_to_sub_corrective_animation" 0
}

$animation "a_delta_bullets_additive_for_offset" "attachment_vm_ar_mcharlie_xmags2_anims\a_delta_bullets_additive_for_offset.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_delta_bullets_additive_for_offset_corrective_animation" 0
}

$sequence "reference" {
	"a_bullets_idle_to_sub"
	"a_delta_bullets_additive_for_offset"
	blend "bullets_offset" 0 30
	blendwidth 2
	delta
	fadein 0.2
	fadeout 0.2
	realtime
}

$keyvalues
{
// CSGO compiler adds the qc_path keyvalue section automatically.
//	qc_path 
//	{
//		"value" "c:\github\source files mw\source-files-mw\attachments\assault rifles\mcharlie\attachment_mag.qc"
//	}
}
